### ISSUE TITLE
Session_12) As a user, I want to view and delete my personal data, so that I have control over my information and comply with GDPR

### ISSUE THREAD

**Issue by OmarSemou** [ITU-BDSA2024-GROUP18/Chirp#102]
**Acceptance Criteria**

**User Information Page**

- The user can view:
   - Name
   - Email
   - Cheeps posted by the user
   - Users they are following

**Forget Me**
   - A Forget Me! button anonymizes or deletes all personal data.
   - The user is logged out after clicking the button.
   - The user cannot log in again with the same credentials.

**Definition of Done**
- The About Me page correctly displays the user's data (name, email, cheeps, following).
- Clicking the Forget Me! button anonymizes or deletes all user information.
- The user is logged out immediately after clicking Forget Me!.
- Attempts to log in with the same credentials fail after anonymization/deletion.
- All features are tested for functionality and GDPR compliance

**Comment by Br00nac** [comment]
Bug! 

When a user that is logged in either through GitHub or a profile registered through the page, the webapp crashes due to an SQL exception, but only if the user is currently following one or more other users. If the user follow no one, the webapp successfully forgets data about the user and deletes their profile.

Specifically, it crashes because a FOREIGN KEY constraint from the Follows table gets violated. I believe this is because we delete the Author table in the database without ensuring all the entries in the Follows table are deleted beforehand.
